#ifndef _CONFIG_H_
#define _CONFIG_H_

#define PIN_LED_ACTIVITY PINB0
#define PORT_LED_ACTIVITY PORTB

#define PIN_SWITCH_DOOR_REED PIND2
#define PORT_SWITCH_DOOR_REED PORTD

#define PIN_RX_RADIO PIND0
#define PIN_TX_RADIO PIND1
#define PORT_RADIO PORTD

#endif
